version: '3.1'

services:
    app:
        build: ./app
        restart: unless-stopped
    proxy:
        build: ./proxy
        restart: unless-stopped
        ports:
            - 80:80
    db:
        build: ./db
        restart: unless-stopped
