version: '3'
services:
  chatwithuser:
    build:
      context: ./src/
      dockerfile: Dockerfile
      args:
        - VULN_1=1
        - BUFFER_SIZE=32
        - VULN_2=0
        - USERNAME_SIZE=40

    ports:
      - "10050:8080"
    restart: unless-stopped

